# ansible-node-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-node
spec:
  replicas: 2
  selector:
    matchLabels:
      role: node
  template:
    metadata:
      labels:
        role: node
    spec:
      containers:
      - name: node
        image: krutika09/rhel-ansible:v1
        ports:
        - containerPort: 22
